logging:
  level:
    root: INFO
    org.springframework: INFO
    com.tu.paquete: DEBUG

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

cors:
  allowed-origins: ${FRONT_URL}

mail:
  host: ${SPRING_MAIL_HOST:smtp.gmail.com}
  port: ${SPRING_MAIL_PORT:587}
  username: ${SPRING_MAIL_USERNAME}
  password: ${SPRING_MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
        starttls:
          enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
